### ISSUE TITLE
Gestion du son

### ISSUE THREAD

**Issue by benoit2600** [Ellda/cassebriques#2]
Le son ne fonctionne pas

**Comment by afonfria** [comment]
Il est commenté. Il fonctionne uniquement sous windows lorsque le code est décommenté.

**Comment by benoit2600** [comment]
C'est corrigé, Nico s'en ai occupé (et ça marche sous Archlinux)

**Comment by afonfria** [comment]
Apparemment Nicolas l'a réparé ^^
